# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6231ea7c3af313dfd4e0c2844f936a381ec8806a409ccb3a5e42645084fbe9482b45c1d4d472025dba5b6a52ebaacc69240f2c35772dbb30f86962650ea2fc98

test:
  secret_key_base: a5a27d61f8dbd5f310e1a2df74b438f1052c86b0777467b41fd90cd376414ae21918bca15722f34fddf01fd43dded9ba3f4f3ea398f1700c4e915704162e359c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
